// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: resume.proto

package data

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_LANGUAGES            Category = 1
	Category_FRONTEND_FRAMEWORKS  Category = 2
	Category_CLOUD_INFRASTRUCTURE Category = 3
	Category_DATA_AI              Category = 4
	Category_TOOLS_OS             Category = 5
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "LANGUAGES",
		2: "FRONTEND_FRAMEWORKS",
		3: "CLOUD_INFRASTRUCTURE",
		4: "DATA_AI",
		5: "TOOLS_OS",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"LANGUAGES":            1,
		"FRONTEND_FRAMEWORKS":  2,
		"CLOUD_INFRASTRUCTURE": 3,
		"DATA_AI":              4,
		"TOOLS_OS":             5,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_resume_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_resume_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{0}
}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,4,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Education     []*Education           `protobuf:"bytes,5,rep,name=education,proto3" json:"education,omitempty"`
	Skills        []*SkillGroup          `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	Publications  []*Publication         `protobuf:"bytes,7,rep,name=publications,proto3" json:"publications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{0}
}

func (x *Resume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resume) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Resume) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Resume) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *Resume) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *Resume) GetSkills() []*SkillGroup {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Resume) GetPublications() []*Publication {
	if x != nil {
		return x.Publications
	}
	return nil
}

type SkillGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      Category               `protobuf:"varint,1,opt,name=category,proto3,enum=resume.Category" json:"category,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillGroup) Reset() {
	*x = SkillGroup{}
	mi := &file_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillGroup) ProtoMessage() {}

func (x *SkillGroup) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillGroup.ProtoReflect.Descriptor instead.
func (*SkillGroup) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{1}
}

func (x *SkillGroup) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *SkillGroup) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type Publication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Conference    string                 `protobuf:"bytes,2,opt,name=conference,proto3" json:"conference,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Description   []string               `protobuf:"bytes,4,rep,name=description,proto3" json:"description,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Skills        []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication) Reset() {
	*x = Publication{}
	mi := &file_resume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication) ProtoMessage() {}

func (x *Publication) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication.ProtoReflect.Descriptor instead.
func (*Publication) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{2}
}

func (x *Publication) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Publication) GetConference() string {
	if x != nil {
		return x.Conference
	}
	return ""
}

func (x *Publication) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Publication) GetDescription() []string {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Publication) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Publication) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Description   []string               `protobuf:"bytes,6,rep,name=description,proto3" json:"description,omitempty"`
	Skills        []string               `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_resume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Job) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Job) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Job) GetDescription() []string {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Job) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

type Education struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        string                 `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Degree        string                 `protobuf:"bytes,2,opt,name=degree,proto3" json:"degree,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_resume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{4}
}

func (x *Education) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Education) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

var File_resume_proto protoreflect.FileDescriptor

const file_resume_proto_rawDesc = "" +
	"\n" +
	"\fresume.proto\x12\x06resume\x1a\x17validate/validate.proto\"\xaa\x02\n" +
	"\x06Resume\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05title\x12\x19\n" +
	"\x03bio\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03bio\x12)\n" +
	"\x04jobs\x18\x04 \x03(\v2\v.resume.JobB\b\xfaB\x05\x92\x01\x02\b\x01R\x04jobs\x12/\n" +
	"\teducation\x18\x05 \x03(\v2\x11.resume.EducationR\teducation\x124\n" +
	"\x06skills\x18\x06 \x03(\v2\x12.resume.SkillGroupB\b\xfaB\x05\x92\x01\x02\b\x01R\x06skills\x127\n" +
	"\fpublications\x18\a \x03(\v2\x13.resume.PublicationR\fpublications\"P\n" +
	"\n" +
	"SkillGroup\x12,\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x10.resume.CategoryR\bcategory\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"\xa5\x01\n" +
	"\vPublication\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"conference\x18\x02 \x01(\tR\n" +
	"conference\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x04 \x03(\tR\vdescription\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\"\xb3\x01\n" +
	"\x03Job\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x06 \x03(\tR\vdescription\x12\x16\n" +
	"\x06skills\x18\a \x03(\tR\x06skills\"c\n" +
	"\tEducation\x12\x16\n" +
	"\x06school\x18\x01 \x01(\tR\x06school\x12\x16\n" +
	"\x06degree\x18\x02 \x01(\tR\x06degree\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end*\x81\x01\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tLANGUAGES\x10\x01\x12\x17\n" +
	"\x13FRONTEND_FRAMEWORKS\x10\x02\x12\x18\n" +
	"\x14CLOUD_INFRASTRUCTURE\x10\x03\x12\v\n" +
	"\aDATA_AI\x10\x04\x12\f\n" +
	"\bTOOLS_OS\x10\x05B&Z$github.com/nikzadkhani/nikzadio/datab\x06proto3"

var (
	file_resume_proto_rawDescOnce sync.Once
	file_resume_proto_rawDescData []byte
)

func file_resume_proto_rawDescGZIP() []byte {
	file_resume_proto_rawDescOnce.Do(func() {
		file_resume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resume_proto_rawDesc), len(file_resume_proto_rawDesc)))
	})
	return file_resume_proto_rawDescData
}

var file_resume_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_resume_proto_goTypes = []any{
	(Category)(0),       // 0: resume.Category
	(*Resume)(nil),      // 1: resume.Resume
	(*SkillGroup)(nil),  // 2: resume.SkillGroup
	(*Publication)(nil), // 3: resume.Publication
	(*Job)(nil),         // 4: resume.Job
	(*Education)(nil),   // 5: resume.Education
}
var file_resume_proto_depIdxs = []int32{
	4, // 0: resume.Resume.jobs:type_name -> resume.Job
	5, // 1: resume.Resume.education:type_name -> resume.Education
	2, // 2: resume.Resume.skills:type_name -> resume.SkillGroup
	3, // 3: resume.Resume.publications:type_name -> resume.Publication
	0, // 4: resume.SkillGroup.category:type_name -> resume.Category
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_resume_proto_init() }
func file_resume_proto_init() {
	if File_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resume_proto_rawDesc), len(file_resume_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resume_proto_goTypes,
		DependencyIndexes: file_resume_proto_depIdxs,
		EnumInfos:         file_resume_proto_enumTypes,
		MessageInfos:      file_resume_proto_msgTypes,
	}.Build()
	File_resume_proto = out.File
	file_resume_proto_goTypes = nil
	file_resume_proto_depIdxs = nil
}
